class OnboardingData {
  static const String topics = "topics";
  static const String writingStyle = "writingStyle";
  static const String conversationTone = "conversationTone";
  static const Map<String, List<String>> onboardingDataMap = {
    topics: [
      "Technology",
      "Coding",
      "Writing",
      "Marketing",
      "Science",
      "Health & Fitness",
      "Web designer",
      "Freelancer",
      "Parenting",
      "Careers",
      "Politics",
      "Music",
      "Entertainment",
      "Sports",
      "Gaming",
      "Fashion & beauty",
      "Food",
      "Business & finance",
      "Arts & culture",
      "Travel",
      "Animation & comics",
      "Family & relationships",
    ],
    writingStyle: [
      "Informative",
      "Conversational",
      "Inspirational",
      "Humorous",
      "Provocative",
      "Personal",
      "Curiosity-driven",
      "Interactive",
      "Timely/Current",
      "Inspirational",
    ],
    conversationTone: [
      "Friendly",
      "Supportive",
      "Collaborative",
      "Appreciative",
      "Inquisitive",
      "Encouraging",
      "Informal",
      "Educational",
      "Problem-solving",
      "Celebratory",
    ],
  };
}
